# Generated by Django 6.0 on 2026-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(help_text='Letters and numbers only, no spaces.', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='We will send login details here.', max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('proof_of_payment', models.ImageField(upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
