# Generated by Django 6.0 on 2026-08-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0002_schoolregistrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Basic, Premium, Enterprise', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly name (e.g., basic-plan)', unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Price per month', max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, help_text='Price per year (usually discounted)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='A short summary of who this plan is for.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this plan from the pricing page.')),
                ('is_highlighted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['monthly_price'],
            },
        ),
        migrations.AddField(
            model_name='schoolregistrationrequest',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annually')], default='monthly', max_length=10),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(help_text='e.g., Up to 500 Students', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='schools_manager.subscriptionplan')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='schoolregistrationrequest',
            name='selected_plan',
            field=models.ForeignKey(blank=True, help_text='The plan they selected on the pricing page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools_manager.subscriptionplan'),
        ),
    ]
