# Generated by Django 6.0 on 2026-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0003_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allocated_storage_mb',
            field=models.FloatField(default=500.0, help_text='Maximum storage allowed in Megabytes'),
        ),
    ]
