# Generated by Django 6.0 on 2026-08-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0004_school_allocated_storage_mb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='allocated_storage_mb',
            new_name='used_storage_mb',
        ),
    ]
