# Generated by Django 6.0 on 2026-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0005_rename_allocated_storage_mb_school_used_storage_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allocated_storage_mb',
            field=models.FloatField(default=500.0, help_text='Maximum storage allowed in Megabytes'),
        ),
        migrations.AlterField(
            model_name='school',
            name='used_storage_mb',
            field=models.FloatField(default=0.0),
        ),
    ]
