# Generated by Django 6.0 on 2026-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0006_school_allocated_storage_mb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Empowering Education Through Technology', max_length=255)),
                ('mission_statement', models.TextField(blank=True, help_text='A short, powerful sentence about your core mission.')),
                ('company_history', models.TextField(blank=True, help_text='The detailed background story of how and why the company started.')),
            ],
            options={
                'verbose_name': 'Company Profile (About Us)',
                'verbose_name_plural': 'Company Profile (About Us)',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-check-circle', help_text='FontAwesome class (e.g., fas fa-bolt)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Three Angels Cloud', max_length=100)),
                ('primary_color', models.CharField(default='#4f46e5', help_text='Hex color code (e.g., #4f46e5)', max_length=7)),
                ('hero_title', models.CharField(default='Manage Your School with Ease', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, help_text='The descriptive text under the main headline.')),
                ('hero_image', models.ImageField(blank=True, help_text='Upload your software mockup dashboard image here.', null=True, upload_to='landing_assets/')),
                ('primary_cta_text', models.CharField(default='Get Started', max_length=50)),
                ('primary_cta_link', models.CharField(default='/apply/', max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, default='View Demo', max_length=50)),
                ('secondary_cta_link', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Landing Page Configuration',
                'verbose_name_plural': 'Landing Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='MediaShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Dashboard Overview, Student Portal Walkthrough', max_length=150)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('image', models.ImageField(blank=True, help_text="Upload if Media Type is 'Image'", null=True, upload_to='showcase_images/')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube or Vimeo link here for faster loading.', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Or upload an MP4 file directly (Keep file size small).', null=True, upload_to='showcase_videos/')),
                ('description', models.TextField(blank=True, help_text='A brief explanation of what is happening in this media.')),
                ('allow_download', models.BooleanField(default=False, help_text="Check this to show a 'Download' button to the public.")),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the landing page')),
            ],
            options={
                'verbose_name': 'Media Showcase Item',
                'verbose_name_plural': 'Media Showcase Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if the user unsubscribes')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., John Doe', max_length=100)),
                ('role', models.CharField(help_text='e.g., Chief Executive Officer (CEO), Lead Developer', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A brief 1-2 sentence description about their expertise.')),
                ('photo', models.ImageField(blank=True, help_text='Upload a professional headshot.', null=True, upload_to='team_photos/')),
                ('linkedin_url', models.URLField(blank=True, help_text='Optional: Link to their LinkedIn profile', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Optional: Link to their X/Twitter profile', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g., put 1 for CEO)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this member from the website')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order'],
            },
        ),
    ]
