# Generated by Django 6.0 on 2026-08-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0007_companyprofile_faq_feature_landingpageconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_bio', models.TextField(default='Pioneering robust multi-tenant architectures for academic institutions worldwide. Built for scale, engineered for security.')),
                ('contact_email', models.EmailField(default='jimc93005@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(default='+265 880 325 161', max_length=50)),
                ('contact_location', models.TextField(default='Malawi\nGlobal Operations Center')),
                ('db_is_operational', models.BooleanField(default=True, help_text='Uncheck to change the indicator to red/offline.')),
                ('engine_version', models.CharField(default='v2.0.0 (Stable)', max_length=50)),
                ('copyright_text', models.CharField(default='© 2026 EduSphere Architectural Engine. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Configuration',
                'verbose_name_plural': 'Footer Configuration',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Privacy Policy or Twitter / X', max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('link_type', models.CharField(choices=[('legal', 'Legal & Privacy'), ('social', 'Social Media')], default='legal', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['display_order'],
            },
        ),
    ]
