# Generated by Django 6.0 on 2026-09-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0008_footerconfig_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., National Bank of Malawi, TNM Mpamba, Airtel Money', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text="Upload the provider's logo (e.g., bank logo, mobile money symbol).", null=True, upload_to='payment_methods/')),
                ('payment_information', models.TextField(help_text='Account details, phone number, or instructions for paying via this method.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this payment method from the page')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['display_order'],
            },
        ),
    ]
