# Generated by Django 6.0 on 2026-09-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0009_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A name for this asset', max_length=150)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('image', 'Picture'), ('document', 'Document')], help_text='Choose whether this is a logo, picture, or document', max_length=20)),
                ('file', models.FileField(help_text='Upload the logo, picture, or document', upload_to='newsletter_assets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active assets will be available when creating newsletters')),
                ('is_temporary', models.BooleanField(default=True, help_text='Temporary assets can be automatically deleted after they are no longer needed')),
            ],
            options={
                'verbose_name': 'Newsletter Asset',
                'verbose_name_plural': 'Newsletter Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
