# Generated by Django 6.0 on 2026-09-10 18:42
import uuid

from django.db import migrations, models


def generate_tokens(apps, schema_editor):
    NewsletterSubscriber = apps.get_model(
        'schools_manager',
        'NewsletterSubscriber'
    )

    for subscriber in NewsletterSubscriber.objects.all():
        subscriber.unsubscribe_token = uuid.uuid4()
        subscriber.save(update_fields=['unsubscribe_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0010_newsletterasset'),
    ]

    operations = [
        # Step 1: Add the field, but don't make it unique yet
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(
                default=None,
                editable=False,
                null=True,
            ),
        ),

        # Step 2: Give every existing subscriber a unique UUID
        migrations.RunPython(
            generate_tokens,
            migrations.RunPython.noop,
        ),

        # Step 3: Now make the field unique and required
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]