# Generated by Django 6.0 on 2026-09-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0011_newslettersubscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools_manager.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='four_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 4 months (Academic Term)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='quarterly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 3 months (Quarterly)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='schoolregistrationrequest',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', '1 Month'), ('quarterly', '3 Months (Quarterly)'), ('four_months', '4 Months (Term)'), ('annual', '12 Months (Annually)')], default='monthly', max_length=15),
        ),
    ]
