# Generated by Django 6.0 on 2026-09-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0012_school_current_plan_school_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', '1 Month'), ('quarterly', '3 Months (Quarterly)'), ('four_months', '4 Months (Term)'), ('annual', '12 Months (Annually)')], default='monthly', max_length=15)),
                ('proof_of_payment', models.ImageField(upload_to='renewal_proofs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='schools_manager.school')),
            ],
            options={
                'verbose_name': 'Subscription Renewal',
                'verbose_name_plural': 'Subscription Renewals',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
