# Generated by Django 6.0 on 2026-09-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0013_subscriptionrenewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name to help you identify this image.', max_length=100)),
                ('image', models.ImageField(help_text='Upload a high-resolution image (e.g., 1920x1080).', upload_to='hero_banners/')),
                ('caption', models.CharField(blank=True, help_text='The text box that appears over the image (optional).', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the image without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
