# Generated by Django 6.0 on 2026-09-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0014_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Searchable description for users.')),
                ('youtube_url', models.URLField(help_text='Paste the full YouTube video link (e.g., https://www.youtube.com/watch?v=...)')),
                ('youtube_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('academics', 'Academics & Grading'), ('finance', 'Finance & Billing'), ('portal', 'Parent & Student Portal'), ('settings', 'System Settings')], default='getting_started', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the video appears.')),
                ('is_published', models.BooleanField(default=True, help_text='Toggle off to hide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demo Video',
                'verbose_name_plural': 'Demo Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
