# Generated by Django 6.0 on 2026-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_manager', '0015_demovideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Upload the promotional graphic here.', upload_to='promos/')),
                ('target_link', models.CharField(help_text='Enter a URL (e.g., https://example.com) or a path (e.g., /apply/)', max_length=255)),
                ('button_text', models.CharField(default='Learn More', help_text='Text for the CTA button.', max_length=50)),
                ('start_time', models.DateTimeField(help_text='When should this promotion start appearing?')),
                ('end_time', models.DateTimeField(help_text='When should this promotion automatically disappear?')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this promotion manually without deleting it.')),
            ],
            options={
                'verbose_name': 'Promotional Block',
                'verbose_name_plural': 'Promotional Blocks',
                'ordering': ['-start_time'],
            },
        ),
    ]
