# Generated by Django 6.0 on 2026-07-02 12:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload a transparent PNG of the signature', null=True, upload_to=users.models.staff_signature_path),
        ),
    ]
