version: '3.8'

services:
  # 1. The Database Service
  db:
    image: postgres:15-alpine
    container_name: school-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  # 2. Your Django App Service
  web:
    build: .
    container_name: school-portal-container
    restart: always
    # Replace 'your_project' with your actual Django project directory name
    command: gunicorn projectfolder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal_network
      - dokploy-network
    labels:

        - "traefik.enable=true"
        - "traefik.http.routers.school-app.rule=Host(`${DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-9-]+}.${DOMAIN}`)"
        - "traefik.http.routers.school-app.entrypoints=websecure"
        - "traefik.http.routers.school-app.tls.certresolver=letsencrypt"
        - "traefik.http.services.school-app.loadbalancer.server.port=8000"
        - "traefik.http.routers.school-app-http.rule=Host(`${DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-9-]+}.${DOMAIN}`)"
        - "traefik.http.routers.school-app-http.entrypoints=web"
        - "traefik.http.routers.school-app-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
# 3. Networks (Isolates DB internally while linking Django to Dokploy's Traefik proxy)
networks:
  internal_network:
    driver: bridge
  dokploy-network:
    external: true

# 4. Persistent Storage (Prevents data loss on restart)
volumes:
  postgres_data:
  static_data:
  media_data: