

services:
  # 1. The Database Service
  db:
    image: postgres:15-alpine
    container_name: school-db
    environment:
      POSTGRES_DB: school_tenant_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Your Django App Service
  web:
    build: .
    container_name: school-portal-container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # This syncs your local code so you don't have to rebuild the image for every small code change!
    ports:
      - "8002:8000"
    environment:
      - DB_NAME=school_tenant_db
      - DB_USER=admin
      - DB_PASSWORD=supersecretpassword
      - POSTGRES_HOST=db      # Overrides .env inside Docker
      - POSTGRES_PORT=5432    # Overrides .env inside Docker
      - DEBUG=True
    depends_on:
      - db

# 3. This ensures your database data isn't deleted if you restart your computer
volumes:
  postgres_data: