# Generated by Django 6.0 on 2026-09-15 16:02

import datetime
import django.core.validators
import timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Timetable', help_text='Name of this timetable configuration.', max_length=100)),
                ('start_time', models.TimeField(default=datetime.time(7, 30), help_text='Time when the first teaching period starts.')),
                ('period_duration', models.PositiveIntegerField(default=40, help_text='Length of a standard teaching period in minutes.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)])),
                ('periods_per_day', models.PositiveIntegerField(default=8, help_text='Maximum number of teaching periods per day.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('working_days', models.JSONField(default=timetable.models.default_working_days, help_text='List of teaching days (0=Monday ... 6=Sunday).', validators=[timetable.models.validate_working_days])),
                ('default_max_teacher_periods_per_day', models.PositiveIntegerField(default=6, help_text='Default max teaching periods for a teacher per day.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('default_max_consecutive_periods', models.PositiveIntegerField(default=3, help_text='Default max consecutive periods a teacher can teach.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True, help_text='Designates if this setting configuration is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timetable Setting',
                'verbose_name_plural': 'Timetable Settings',
            },
        ),
    ]
