# Generated by Django 6.0 on 2026-09-15 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Tea Break, Lunch, Assembly', max_length=50)),
                ('after_period', models.PositiveIntegerField(help_text='Period number after which this break occurs (e.g., after period 3).')),
                ('duration', models.PositiveIntegerField(help_text='Duration of break in minutes.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timetable.timetablesettings')),
            ],
            options={
                'ordering': ['after_period'],
                'unique_together': {('settings', 'after_period')},
            },
        ),
    ]
