# Generated by Django 6.0 on 2026-09-15 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_document_file_size_mb'),
        ('timetable', '0002_timetablebreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full room name, e.g., 'Science Laboratory 1'.", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short code for timetable grid display, e.g., 'LAB-1'.", max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'General Classroom'), ('LABORATORY', 'Science Laboratory'), ('COMPUTER_LAB', 'Computer Lab'), ('WORKSHOP', 'Technical Workshop'), ('HALL', 'Main Hall / Auditorium'), ('SPORTS', 'Sports Field / Gym'), ('OTHER', 'Other Special Facility')], db_index=True, default='CLASSROOM', help_text='Category used for subject room allocation rules.', max_length=20)),
                ('building', models.CharField(blank=True, help_text="Building or block location, e.g., 'Science Wing'.", max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum student seating capacity.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls room availability for auto-scheduling.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timetable Room',
                'verbose_name_plural': 'Timetable Rooms',
                'ordering': ['room_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignmentConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveIntegerField(default=5, help_text='Total teaching periods allocated per week for this assignment.', validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_double_periods', models.BooleanField(default=True, help_text='Whether consecutive periods (double periods) are allowed.')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_constraint', to='students_app.teachingassignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRoomRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_room_type', models.CharField(choices=[('CLASSROOM', 'General Classroom'), ('LABORATORY', 'Science Laboratory'), ('COMPUTER_LAB', 'Computer Lab'), ('WORKSHOP', 'Technical Workshop'), ('HALL', 'Main Hall / Auditorium'), ('SPORTS', 'Sports Field / Gym'), ('OTHER', 'Other Special Facility')], default='CLASSROOM', help_text='Minimum room type needed for this subject.', max_length=20)),
                ('subject', models.OneToOneField(help_text='The subject that requires a specific room type.', on_delete=django.db.models.deletion.CASCADE, related_name='room_requirement', to='students_app.subject')),
                ('specific_room', models.ForeignKey(blank=True, help_text='Optional override to force a specific room.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetableroom')),
            ],
        ),
    ]
