# Generated by Django 6.0 on 2026-09-15 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetableroom_teachingassignmentconstraint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this timetable, e.g., '2026 Term 1 Main'.", max_length=100)),
                ('academic_year', models.PositiveIntegerField(help_text='Academic year this timetable belongs to (e.g., 2026).')),
                ('term', models.PositiveIntegerField(help_text='Term number: 1, 2, or 3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Draft (editing), Published (visible), or Archived (historical).', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Designates if this is the currently running timetable for the school.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(help_text='Timetable rules and periods used to generate this version.', on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='timetable.timetablesettings')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-academic_year', '-term', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'academic_year', 'term'), name='unique_timetable_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_timetable')],
            },
        ),
    ]
