# Generated by Django 6.0 on 2026-09-15 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_document_file_size_mb'),
        ('timetable', '0004_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, help_text='Day of the week.')),
                ('period_number', models.PositiveIntegerField(db_index=True, help_text='Period index (1 for Period 1, 2 for Period 2, etc.).', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Controls entry activation state.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='The teacher, subject, and class level assignment being scheduled.', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='students_app.teachingassignment')),
                ('room', models.ForeignKey(blank=True, help_text='The physical room or laboratory assigned for this period slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.timetableroom')),
                ('timetable', models.ForeignKey(help_text='The specific timetable version this slot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['timetable', 'day', 'period_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('timetable', 'room', 'day', 'period_number'), name='unique_room_slot_per_timetable')],
            },
        ),
    ]
