# Generated by Django 6.0 on 2026-09-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_document_file_size_mb'),
        ('timetable', '0005_timetableentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='assignment',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='The subject instance containing the teacher and target class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='students_app.subject'),
        ),
    ]
