# Generated by Django 6.0 on 2026-09-16 20:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_document_file_size_mb'),
        ('timetable', '0006_remove_timetableentry_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveIntegerField(default=5, help_text='Total teaching periods allocated per week for this subject.', validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_double_periods', models.BooleanField(default=True, help_text='Whether consecutive periods (double periods) are allowed.')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_constraint', to='students_app.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='TeachingAssignmentConstraint',
        ),
    ]
