# Generated by Django 6.0 on 2026-09-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_subjectconstraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectconstraint',
            name='double_periods_per_week',
            field=models.PositiveIntegerField(default=0, help_text='How many double periods should this subject have per week? (e.g., 2 for Mathematics)'),
        ),
    ]
