# Generated by Django 6.0 on 2026-09-20 19:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_subjectconstraint_double_periods_per_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week.')),
                ('period_number', models.PositiveIntegerField(help_text='Period index to block (e.g., 8 for Period 8).', validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(help_text="Reason for blocking, e.g., 'Clubs', 'Assembly'", max_length=50)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='timetable.timetablesettings')),
            ],
            options={
                'ordering': ['day', 'period_number'],
                'unique_together': {('settings', 'day', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week.')),
                ('period_number', models.PositiveIntegerField(blank=True, help_text='Leave blank to mark the whole day as unavailable. Otherwise, specify the period number.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(blank=True, help_text="e.g., 'Part-time off', 'Admin duties'", max_length=100)),
                ('teacher', models.ForeignKey(help_text='The teacher who is unavailable.', on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teacher Unavailabilities',
                'unique_together': {('teacher', 'day', 'period_number')},
            },
        ),
    ]
