# Generated by Django 6.0 on 2025-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Chichewa', 'Chichewa'), ('Agriculture', 'Agriculture'), ('Geography', 'Geography'), ('Life Skills', 'Life Skills'), ('Social', 'Social'), ('History', 'History')], max_length=20)),
                ('subject_teacher', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('class_level', models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4')], max_length=10)),
                ('year_enrolled', models.IntegerField(blank=True, choices=[(2025, 2025), (2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020)], null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('disability', models.CharField(max_length=20)),
                ('parental_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('orphanhood', models.CharField(blank=True, choices=[('Both parents alive', 'Both parents alive'), ('Single orphan', 'Single orphan'), ('Double orphan', 'Double orphan')], max_length=20, null=True)),
                ('class_teachers_comment', models.CharField(blank=True, null=True)),
                ('Headteachers_comment', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ManyToManyField(blank=True, to='students_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('academic_year', models.CharField(max_length=10)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students_app.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'academic_year', 'term')},
            },
        ),
    ]
