# Generated by Django 6.0 on 2026-04-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='form_teacher',
            field=models.OneToOneField(blank=True, help_text='The teacher responsible for this entire class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_form_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='students',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.classlevel'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students_app.students'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students_app.students'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='students_app.department'),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='students_app.subdepartment'),
        ),
        migrations.AddField(
            model_name='subdepartmentrole',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='students_app.subdepartment'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_instances', to='students_app.mastersubject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='students_app.classlevel'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='students',
            name='subject',
            field=models.ManyToManyField(blank=True, to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='subjectdepartment',
            name='head_of_department',
            field=models.OneToOneField(blank=True, help_text='The HOD responsible for this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_headed_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subjectdepartment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.classlevel'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='subdepartmentrole',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='students_app.teacher'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students_app.classlevel'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students_app.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'target_class')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'subject', 'class_level')},
        ),
    ]
