# Generated by Django 6.0 on 2025-12-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Chichewa', 'Chichewa'), ('Agriculture', 'Agriculture'), ('Geography', 'Geography'), ('Life Skills', 'Life Skills'), ('Social', 'Social'), ('History', 'History'), ('Biology', 'Biology')], max_length=20),
        ),
    ]
