# Generated by Django 6.0 on 2025-12-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3'), ('4', 'Term 4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='class_level',
            field=models.CharField(choices=[('1', 'Form 1'), ('2', 'Form 2'), ('3', 'Form 3'), ('4', 'Form 4')], max_length=10),
        ),
    ]
