# Generated by Django 6.0 on 2026-07-02 12:28

import students_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='headteacher_signature',
            field=models.ImageField(blank=True, help_text="Upload the Headteacher's signature (Transparent PNG preferred)", null=True, upload_to=students_app.models.tenant_logo_path),
        ),
    ]
