# Generated by Django 6.0 on 2026-07-02 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_schoolprofile_headteacher_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='classlevel',
            options={'ordering': ['level_order']},
        ),
        migrations.AddField(
            model_name='classlevel',
            name='level_order',
            field=models.IntegerField(default=0, help_text='Used to sort classes (e.g., 1 for Form 1, 2 for Form 2)'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_letter_snapshot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='remark_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='class_level',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='class_level_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('grade_name', models.CharField(max_length=10)),
                ('remark', models.CharField(max_length=100)),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='students_app.gradingsystem')),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
        migrations.AddField(
            model_name='classlevel',
            name='grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.gradingsystem'),
        ),
    ]
