# Generated by Django 6.0 on 2026-07-09 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_gradingsystem_alter_classlevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeboundary',
            name='max_score',
            field=models.FloatField(help_text='Enter a value between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='gradeboundary',
            name='min_score',
            field=models.FloatField(help_text='Enter a value between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
