# Generated by Django 6.0 on 2025-12-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_alter_grade_term_alter_students_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='class_level',
            field=models.CharField(choices=[('1', 'Form 1'), ('2', 'Form 2'), ('3', 'Form 3'), ('4', 'Form 4')], max_length=10),
        ),
    ]
