# Generated by Django 6.0 on 2026-07-09 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_alter_gradeboundary_max_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectdepartment',
            options={'ordering': ['departments'], 'verbose_name': 'Subject Department', 'verbose_name_plural': 'Subject Departments'},
        ),
        migrations.AddField(
            model_name='subjectdepartment',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Briefly describe the focus of this department.', null=True),
        ),
        migrations.AlterField(
            model_name='subjectdepartment',
            name='departments',
            field=models.CharField(default='general', help_text='Enter the department name (e.g., Science, Languages, Humanities)', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectdepartment',
            name='head_of_department',
            field=models.OneToOneField(blank=True, help_text='The HOD responsible for this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL),
        ),
    ]
