# Generated by Django 6.0 on 2026-01-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_schoolprofile_alter_students_year_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
