# Generated by Django 6.0 on 2026-07-12 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0007_alter_classlevel_form_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdepartment',
            name='head_of_department',
            field=models.OneToOneField(blank=True, help_text='The HOD responsible for this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_headed_department', to=settings.AUTH_USER_MODEL),
        ),
    ]
