# Generated by Django 6.0 on 2026-01-31 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0008_department_subdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='students_app.subdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HEAD', 'Head of Department'), ('VICE', 'Vice Head'), ('MEMBER', 'Member')], max_length=10)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='students_app.subdepartment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='students_app.teacher')),
            ],
        ),
    ]
