# Generated by Django 6.0 on 2026-08-08 17:37

import django.utils.timezone
import students_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0008_alter_subjectdepartment_head_of_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Shortlisted Candidates for 2026/2027', max_length=200)),
                ('category', models.CharField(blank=True, help_text='e.g., General, Admissions, Alert', max_length=100)),
                ('content', models.TextField(help_text='The full text of the announcement.')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this from the homepage.')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Dr. John Doe', max_length=150)),
                ('role', models.CharField(help_text='e.g., Executive Dean: School of Education', max_length=150)),
                ('photo', models.ImageField(upload_to=students_app.models.leadership_photo_path)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order they appear on the site (1 comes first, then 2, etc.)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(help_text='Upload an image for the news card.', upload_to=students_app.models.news_image_path)),
                ('summary', models.TextField(help_text='A short 2-3 line excerpt for the homepage.', max_length=300)),
                ('body', models.TextField(help_text='The full news article content.')),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-publish_date'],
            },
        ),
    ]
