# Generated by Django 6.0 on 2026-02-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0009_teacher_departmentevent_subdepartmentrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='employment_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
