# Generated by Django 6.0 on 2026-08-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0009_announcement_leadershipprofile_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_text', models.CharField(help_text='e.g., 14th Sept 2026 or Week 1', max_length=100)),
                ('activity', models.CharField(help_text='e.g., School Opens for Term 1', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Used to keep events in chronological order')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
