# Generated by Django 6.0 on 2026-08-11 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0010_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(blank=True, help_text='e.g. Excellence in Character and Learning', max_length=255)),
                ('vision_statement', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('postal_address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'School Profile & Settings',
                'verbose_name_plural': 'School Profile & Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Ministry Registration Certificate', max_length=150)),
                ('document_file', models.FileField(upload_to='legal_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students_app.footer')),
            ],
        ),
    ]
