# Generated by Django 6.0 on 2026-02-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0010_teacher_gender_teacher_employment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Gender',
            new_name='gender',
        ),
    ]
