# Generated by Django 6.0 on 2026-02-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0011_rename_gender_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employment_number',
            field=models.IntegerField(unique=True),
        ),
    ]
