# Generated by Django 6.0 on 2026-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0011_footer_footerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size_mb',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
