# Generated by Django 6.0 on 2026-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_document_file_size_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='disability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
